version: '3.8'

services:
  sqlserver:
    container_name: SQL_server
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
     - 1433:1433
    environment:
      - MSSQL_SA_PASSWORD=TaJnEhEsLo!!!123456789
      - ACCEPT_EULA=Y
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secret
